name = "tuple"
authors = [ "CoffeeTableEspresso <coffeetableespresso@gmail.com>" ]
version = "v0.1.0"
license = "MIT"

[build]
sources = [ "tuple.c" ]
scripts = [ "tuple.yasl" ]
includes = [ "yasl", "yasl/interpreter", "yasl/util" ]

[deps]
