name = "tuple"
authors = [ "CoffeeTableEspresso <coffeetableespresso@gmail.com>" ]
version = "v0.1.2"
license = "MIT"

[build]
sources = [ "tuple.c" ]
scripts = [ "tuple.yasl" ]
includes = [ "yasl/src", "yasl/src/interpreter", "yasl/src/data-structures", "yasl/src/util" ]

[deps]
